name: ControlSysWorkflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.0-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 .

    - name: Codestyle by black
      run: black src/

    - name: Sorting imports with isort
      run: isort src/

    - name: Run pytest
      run: |
        pytest
        env:
          name: Run pytest
        run: pytest
        env:
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          MODE=DEV
          TEST_DB=postgres
